# fly.toml app configuration file generated for critiplot on 2025-09-30T20:21:37+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'critiplot'
primary_region = 'bom'

[build]
  builder = 'paketobuildpacks/builder:full'

[processes]
  app = 'streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true'

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
